### ISSUE TITLE
Strange translucence

### ISSUE THREAD

**Issue by benio1394** [Darkhax/Bone-Zone#10]
Here is a picture of strange translucence with carcass. Even the caves are visible
![2023-01-04_17 48 43](https://user-images.githubusercontent.com/51888209/210606636-40d13c87-7bea-48dc-811c-5d11b9b16ebc.png)

**Comment by AxelCornelisPXL** [comment]
are you using the latest version of the mod ? 
do you have optifine or any other graphic optimisation mods installed ? 
try disabling the graphic enhancement mods if you got any and see if it the issue persists

**Comment by benio1394** [comment]
Yes, I use the newest version and I have sodium, lithium, spark and indium

**Comment by Darkhax** [comment]
This issue is specifically caused by performance mods. I made an update to the Bookshelf library which aims to improve compatibility and I've heard the performance mods have also made some improvements. Try updating to Bookshelf 16.2.18 or newer. If that still doesn't work, unfortunately there's not much else we can do about the performance mods.
